export enum ActionRejectCode {
  WrongPhase = 'wrong_phase',
  NotYourTurn = 'not_your_turn',
  LobbyNotEnoughPlayers = 'lobby_not_enough_players',
  InsufficientResources = 'insufficient_resources',
  IllegalPlacement = 'illegal_placement',
  InvalidPayload = 'invalid_payload',
  LobbyFull = 'lobby_full',
  UnknownLobby = 'unknown_lobby',
  LobbyAlreadyExists = 'lobby_already_exists',
  LobbyHostOnly = 'lobby_host_only',
  PlayerNotInLobby = 'player_not_in_lobby',
  UnknownTrade = 'unknown_trade',
  TradeNotOpen = 'trade_not_open',
  InvalidTradeTransition = 'invalid_trade_transition',
  NoDevCardAvailable = 'no_dev_card_available',
  DevCardNotOwned = 'dev_card_not_owned',
  DevCardAlreadyPlayed = 'dev_card_already_played',
  DevCardBoughtThisTurn = 'dev_card_bought_this_turn',
  InvalidBankTrade = 'invalid_bank_trade',
  VictimRequired = 'victim_required',
  RobberSameTile = 'robber_same_tile',
  GameFinished = 'game_finished',
  Unknown = 'unknown',
}
