export enum ActionRejectCode {
  WrongPhase = 'wrong_phase',
  NotYourTurn = 'not_your_turn',
  InsufficientResources = 'insufficient_resources',
  IllegalPlacement = 'illegal_placement',
  InvalidPayload = 'invalid_payload',
  LobbyFull = 'lobby_full',
  UnknownLobby = 'unknown_lobby',
  PlayerNotInLobby = 'player_not_in_lobby',
  UnknownTrade = 'unknown_trade',
  TradeNotOpen = 'trade_not_open',
  NoDevCardAvailable = 'no_dev_card_available',
  DevCardNotOwned = 'dev_card_not_owned',
  InvalidBankTrade = 'invalid_bank_trade',
  VictimRequired = 'victim_required',
  GameFinished = 'game_finished',
}
